language: python                                                                                                                                                                                              

before_script:
- pip install tox

# test script
script:  tox

matrix:
   include:
     - python: 2.6
       env: TOXENV=py26-django14
     - python: 2.6
       env: TOXENV=py26-django15
     - python: 2.6
       env: TOXENV=py26-django16
     - python: 2.7
       env: TOXENV=py27-django14
     - python: 2.7
       env: TOXENV=py27-django15
     - python: 2.7
       env: TOXENV=py27-django16
     - python: 2.7
       env: TOXENV=py27-django17
     - python: 2.7
       env: TOXENV=py27-django18
     - python: 2.7
       env: TOXENV=py27-django19
     - python: 2.7
       env: TOXENV=py27-django_trunk
     - python: 3.3
       env: TOXENV=py33-django15
     - python: 3.3
       env: TOXENV=py33-django16
     - python: 3.3
       env: TOXENV=py33-django17
     - python: 3.3
       env: TOXENV=py33-django18
     - python: 3.4
       env: TOXENV=py34-django15
     - python: 3.4
       env: TOXENV=py34-django16
     - python: 3.4
       env: TOXENV=py34-django17
     - python: 3.4
       env: TOXENV=py34-django18
     - python: 3.4
       env: TOXENV=py34-django19
     - python: 3.4
       env: TOXENV=py34-django_trunk
     - python: 3.5
       env: TOXENV=py35-django15
     - python: 3.5
       env: TOXENV=py35-django16
     - python: 3.5
       env: TOXENV=py35-django17
     - python: 3.5
       env: TOXENV=py35-django18
     - python: 3.5
       env: TOXENV=py35-django19
     - python: 3.5
       env: TOXENV=py35-django_trunk
